### ISSUE TITLE
Enregistrement email ? 

### ISSUE THREAD

**Issue by jmreymond** [Sovxx/matchid-wikidata#1]
Message retourné par deces.matchid.io : No token provided and temporary anonymous usage expired, please register with email or wait 24 hours
Traceback (most recent call last):
  File "/home/jmax/Wikipédia/Outils/matchid/matchid-wikidata-main/matchid-wikidata.py", line 208, in <module>
    print("i: ", i,"  k: ", k, "  m:", m,"  response size :", res['response']['total'])
KeyError: 'response'

Comment renseigner un email de connexion à matchid, fichier de configuration ?
merci,

**Comment by Sovxx** [comment]
modification intégrée
