### ISSUE TITLE
item non trouvé dans matchid

### ISSUE THREAD

**Issue by jmreymond** [Sovxx/matchid-wikidata#5]
Un certain nombre passe à côté et j'ai des soupcons que cela provienne des caractères accentués.
Par exemple avec  René Barnérias (Q3425798) , le programme avec les paramètres
Date (incluse) de début ? (ex: 1970-01-01) : 2011-02-13
Date (non incluse) de fin ? (ex: 1970-02-01) : 2011-02-14
trouve bien dans wikidata mais pas dans matchid alors qu'à l'exception du lieu de décès pas assez précis, tout devrait bien aller
https://deces.matchid.io/id/MItNkX3xm89E

idem avec  Maïna Kataki (Q3303405)  où on ne match pas 
https://deces.matchid.io/id/DCo12QU_x_GC

**Comment by jmreymond** [comment]
cela doit être autre chose car
 Megumi Satsu (Q2741083)  est simple à trouver, sans accents
https://deces.matchid.io/id/g9lFbFUCm3yQ
et pourtant échec.

**Comment by Sovxx** [comment]
problème réglé,
sauf pour Maïna Kataki qui n'apparait pas via une recherche directe : https://deces.matchid.io/search?q=Ma%C3%AFna+Kataki
