### ISSUE TITLE
Plantage sur empty request

### ISSUE THREAD

**Issue by jmreymond** [Sovxx/matchid-wikidata#7]
En lançant sur le créneau 1999-01-01, 2001-01-01, le programme s'arrête très rapidement sur le dénommé Fulcanelli Q659195

----- i: 33  /  1098 (3.0%) (ETA: 106.5 min)  -----  Q659195   Fulcanelli
['Q659195', 'Fulcanelli', '', '', '', '', '', '', '', '', '', '']
i:  33   k:  33   m: 0
{'q': 'Fulcanelli ', 'size': 20}
i:  33   k:  33   m: 0   response size : 82
i:  33   k:  33   m: 0   scored size : 0
i:  33   k:  33   m: 0   on affiche quand même le 1er résultat avec un score 0.001
i:  33   k:  33   m: 1
{'birthCity': '',
 'birthDate': '',
 'deathCity': '',
 'deathDate': '',
 'lastName': 'Fulcanelli',
 'size': 20}
i:  33   k:  33   m: 1   response size : 82
i:  33   k:  33   m: 1   scored size : 0
i:  33   k:  33   m: 1   on affiche quand même le 1er résultat avec un score 0.001
i:  33   k:  33   m: 2
{'birthCity': '',
 'birthDate': '',
 'deathCity': '',
 'deathDate': '',
 'firstName': '',
 'lastName': '',
 'size': 20}
PROBLEME DE REPONSE =========================================== Message retourné par deces.matchid.io : error - empty request
PROBLEME DE REPONSE ===========================================
{'msg': 'error - empty request'}
Traceback (most recent call last):
  File "/home/jmax/Wikipédia/Outils/matchid/matchid-wikidata-main/matchid-wikidata.py", line 251, in <module>
    for o in range(min(res['response']['total'],20)):
KeyError: 'response'

**Comment by jmreymond** [comment]
plus rapide avec ce créneau

Date (incluse) de début ? (ex: 1970-01-01) : 1999-12-31
Date (non incluse) de fin ? (ex: 1970-02-01) : 2000-01-02

**Comment by Sovxx** [comment]
merci pour l'information !
résolu maintenant
